### ISSUE TITLE
Publish multi-arch docker images

### ISSUE THREAD

**Issue by pfrybar** [vispana/vispana#28]
First off, thanks for the great project!

I was hoping you could start building and publishing [multi-arch](https://docs.docker.com/desktop/multi-arch/) docker images. When I run the docker container locally on my M1 MacBook I get a failure, even with emulation turned on (with the `--platform` option):

```
❯ docker run --rm -p 4000:4000 --platform linux/amd64 vispana/vispana
qemu: uncaught target signal 11 (Segmentation fault) - core dumped
```

**Comment by buinauskas** [comment]
Cloning the repository and doing the following change builds the image successfully using `docker build -t internal/vispana .`

```diff
-FROM elixir:1.12
+FROM elixir:1.14
```

The application will launch successfully, but once I try to connect to any of the vespa clusters, the app will raise exceptions.
```
[error] GenServer #PID<0.646.0> terminating
** (Protocol.UndefinedError) protocol Enumerable not implemented for nil of type Atom
    (elixir 1.14.5) lib/enum.ex:1: Enumerable.impl_for!/1
    (elixir 1.14.5) lib/enum.ex:166: Enumerable.reduce/3
    (elixir 1.14.5) lib/enum.ex:4307: Enum.reverse/1
    (elixir 1.14.5) lib/enum.ex:1374: Enum.group_by/3
    (vispana 0.1.0) lib/vispana/clusterloader.ex:116: Vispana.ClusterLoader.build_content_cluster/2
    (elixir 1.14.5) lib/enum.ex:1658: Enum."-map/2-lists^map/1-0-"/2
    (vispana 0.1.0) lib/vispana/clusterloader.ex:53: Vispana.ClusterLoader.vespa_cluster_loader/1
    (vispana 0.1.0) lib/vispana/clusterloader.ex:27: Vispana.ClusterLoader.load/1
    (vispana 0.1.0) lib/vispana_web/live/common_live/index.ex:142: VispanaWeb.VispanaCommon.vespa_cluster_load/1
    (vispana 0.1.0) lib/vispana_web/live/common_live/index.ex:22: VispanaWeb.VispanaCommon.mount/3
    (phoenix_live_view 0.15.7) lib/phoenix_live_view/utils.ex:320: anonymous fn/4 in Phoenix.LiveView.Utils.maybe_call_live_view_mount!/4
    (telemetry 0.4.3) /app/deps/telemetry/src/telemetry.erl:272: :telemetry.span/3
    (phoenix_live_view 0.15.7) lib/phoenix_live_view/channel.ex:886: Phoenix.LiveView.Channel.verified_mount/5
    (phoenix_live_view 0.15.7) lib/phoenix_live_view/channel.ex:57: Phoenix.LiveView.Channel.handle_info/2
    (stdlib 5.0.2) gen_server.erl:1077: :gen_server.try_handle_info/3
    (stdlib 5.0.2) gen_server.erl:1165: :gen_server.handle_msg/6
    (stdlib 5.0.2) proc_lib.erl:241: :proc_lib.init_p_do_apply/3
Last message: {Phoenix.Channel, %{"params" => %{"_csrf_token" => "DwZPLDM3F00bKixzGAEOXj83HBkAMHgNzn6KDZgyNNh2ljB-UBtVrTIh", "_mounts" => 0, "_track_static" => ["http://localhost:4000/css/app.css", "http://localhost:4000/js/app.js", "http://localhost:4000/img/icons8-hive-64.png"]}, "session" => "SFMyNTY.g2gDaAJhBHQAAAAHdwJpZG0AAAAUcGh4LUY0R2NsaDVRQmI5LU9RRlJ3BHZpZXd3I0VsaXhpci5WaXNwYW5hV2ViLkNvbnRlbnRMaXZlLkluZGV4dwdzZXNzaW9udAAAAAB3CnBhcmVudF9waWR3A25pbHcGcm91dGVydxhFbGl4aXIuVmlzcGFuYVdlYi5Sb3V0ZXJ3CHJvb3RfcGlkdwNuaWx3CXJvb3Rfdmlld3cjRWxpeGlyLlZpc3BhbmFXZWIuQ29udGVudExpdmUuSW5kZXhuBgDLTcVeigFiAAFRgA.oG9IjNmDWCIdr2ZMaMv3b75-bmx37VutgRtKFDP5RE8", "static" => "SFMyNTY.g2gDaAJhBHQAAAADdwJpZG0AAAAUcGh4LUY0R2NsaDVRQmI5LU9RRlJ3BWZsYXNodAAAAAB3CmFzc2lnbl9uZXdqbgYAy03FXooBYgABUYA.aAjg8YKrfHOJqNsr-LEkWuaPk3WX_8y_pWS0TJZt-jw", "url" => "http://localhost:4000/content?config_host=http://remote-vespa-cfg1.internal.net:19071"}, {#PID<0.641.0>, #Reference<0.912252604.2289827842.219807>}, %Phoenix.Socket{assigns: %{}, channel: Phoenix.LiveView.Channel, channel_pid: nil, endpoint: VispanaWeb.Endpoint, handler: Phoenix.LiveView.Socket, id: nil, joined: false, join_ref: "4", private: %{connect_info: %{session: %{"_csrf_token" => "uhygwmp4UdDAtkLsjuhOrd1e"}}}, pubsub_server: Vispana.PubSub, ref: nil, serializer: Phoenix.Socket.V2.JSONSerializer, topic: "lv:phx-F4Gclh5QBb9-OQFR", transport: :websocket, transport_pid: #PID<0.641.0>}}
State: #Reference<0.912252604.2289827842.219810>
[error] an exception was raised:
    ** (Protocol.UndefinedError) protocol Enumerable not implemented for nil of type Atom
        (elixir 1.14.5) lib/enum.ex:1: Enumerable.impl_for!/1
        (elixir 1.14.5) lib/enum.ex:166: Enumerable.reduce/3
        (elixir 1.14.5) lib/enum.ex:4307: Enum.reverse/1
        (elixir 1.14.5) lib/enum.ex:1374: Enum.group_by/3
        (vispana 0.1.0) lib/vispana/clusterloader.ex:116: Vispana.ClusterLoader.build_content_cluster/2
        (elixir 1.14.5) lib/enum.ex:1658: Enum."-map/2-lists^map/1-0-"/2
        (vispana 0.1.0) lib/vispana/clusterloader.ex:53: Vispana.ClusterLoader.vespa_cluster_loader/1
        (vispana 0.1.0) lib/vispana/clusterloader.ex:27: Vispana.ClusterLoader.load/1
        (vispana 0.1.0) lib/vispana_web/live/common_live/index.ex:142: VispanaWeb.VispanaCommon.vespa_cluster_load/1
        (vispana 0.1.0) lib/vispana_web/live/common_live/index.ex:22: VispanaWeb.VispanaCommon.mount/3
        (phoenix_live_view 0.15.7) lib/phoenix_live_view/utils.ex:320: anonymous fn/4 in Phoenix.LiveView.Utils.maybe_call_live_view_mount!/4
        (telemetry 0.4.3) /app/deps/telemetry/src/telemetry.erl:272: :telemetry.span/3
        (phoenix_live_view 0.15.7) lib/phoenix_live_view/channel.ex:886: Phoenix.LiveView.Channel.verified_mount/5
        (phoenix_live_view 0.15.7) lib/phoenix_live_view/channel.ex:57: Phoenix.LiveView.Channel.handle_info/2
        (stdlib 5.0.2) gen_server.erl:1077: :gen_server.try_handle_info/3
        (stdlib 5.0.2) gen_server.erl:1165: :gen_server.handle_msg/6
        (stdlib 5.0.2) proc_lib.erl:241: :proc_lib.init_p_do_apply/3
```

**Comment by broknloop** [comment]
Should be fixed by https://github.com/vispana/vispana/pull/31 and https://github.com/vispana/vispana/pull/32
