### ISSUE TITLE
 Missing HTTP2-Settings header

### ISSUE THREAD

**Issue by YashasviMantha** [vispana/vispana#83]
When trying to start the vispana as a container in the local machine with the vespa config service running at a remote machine, I get the following error:

```
2024-09-19T06:29:34.137Z ERROR 1 --- [mcat-handler-10] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed: java.lang.RuntimeException: java.lang.RuntimeException: Failed to get prerequisites from Vespa] with root cause

org.springframework.web.client.HttpClientErrorException$BadRequest: 400 Bad Request: "<h1>Bad Message 400</h1><pre>reason: Missing HTTP2-Settings header</pre>"
	at org.springframework.web.client.HttpClientErrorException.create(HttpClientErrorException.java:103) ~[spring-web-6.1.1.jar!/:6.1.1]
	at org.springframework.web.client.StatusHandler.lambda$defaultHandler$3(StatusHandler.java:86) ~[spring-web-6.1.1.jar!/:6.1.1]
	at org.springframework.web.client.StatusHandler.handle(StatusHandler.java:146) ~[spring-web-6.1.1.jar!/:6.1.1]
	at org.springframework.web.client.DefaultRestClient$DefaultResponseSpec.applyStatusHandlers(DefaultRestClient.java:654) ~[spring-web-6.1.1.jar!/:6.1.1]
	at org.springframework.web.client.DefaultRestClient.readWithMessageConverters(DefaultRestClient.java:192) ~[spring-web-6.1.1.jar!/:6.1.1]
	at org.springframework.web.client.DefaultRestClient$DefaultResponseSpec.readBody(DefaultRestClient.java:641) ~[spring-web-6.1.1.jar!/:6.1.1]
	at org.springframework.web.client.DefaultRestClient$DefaultResponseSpec.body(DefaultRestClient.java:589) ~[spring-web-6.1.1.jar!/:6.1.1]
	at com.vispana.vespa.state.helpers.Request.requestGet(Request.java:10) ~[!/:0.0.1-SNAPSHOT]
	at com.vispana.vespa.state.helpers.VespaVersionFetcher.fetch(VespaVersionFetcher.java:13) ~[!/:0.0.1-SNAPSHOT]
	at com.vispana.vespa.state.VespaStateClient.lambda$vespaState$0(VespaStateClient.java:21) ~[!/:0.0.1-SNAPSHOT]
	at java.base/java.util.concurrent.StructuredTaskScope$SubtaskImpl.run(StructuredTaskScope.java:889) ~[na:na]
	at java.base/java.lang.VirtualThread.run(VirtualThread.java:309) ~[na:na]


```

The following are the specific steps I follow:

```
docker run -p 4000:4000 vispana/vispana

Enter the config url: http://vespa-config.example.com

Greeted with the above error.
```

Happy to share more information. Thanks!

**Comment by broknloop** [comment]
Thanks for reporting. What version of Vespa are you running?

**Comment by YashasviMantha** [comment]
This issue is reproducible on v8.524.25
